//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1_2025_Chumakov
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapisi
    {
        public int id { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<System.DateTime> data_rozhdenie { get; set; }
        public Nullable<int> id_regiona { get; set; }
        public Nullable<int> id_strani { get; set; }
        public Nullable<int> id_role { get; set; }
        public string Email { get; set; }
        public string Nomer_telephona { get; set; }
        public string password { get; set; }
    
        public virtual region region { get; set; }
        public virtual roole roole { get; set; }
        public virtual Strani Strani { get; set; }
    }
}
